//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 12:21:01 PM EDT 
//


package com.mhe.rest.datacash.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link TxnDetails }
     * 
     */
    public TxnDetails createTxnDetails() {
        return new TxnDetails();
    }

    /**
     * Create an instance of {@link TxnDetails.AirlinesDetails }
     * 
     */
    public TxnDetails.AirlinesDetails createTxnDetailsAirlinesDetails() {
        return new TxnDetails.AirlinesDetails();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan }
     * 
     */
    public TxnDetails.The3RdMan createTxnDetailsThe3RdMan() {
        return new TxnDetails.The3RdMan();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan.OrderInformation }
     * 
     */
    public TxnDetails.The3RdMan.OrderInformation createTxnDetailsThe3RdManOrderInformation() {
        return new TxnDetails.The3RdMan.OrderInformation();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan.OrderInformation.Products }
     * 
     */
    public TxnDetails.The3RdMan.OrderInformation.Products createTxnDetailsThe3RdManOrderInformationProducts() {
        return new TxnDetails.The3RdMan.OrderInformation.Products();
    }

    /**
     * Create an instance of {@link TxnDetails.ThreeDSecure }
     * 
     */
    public TxnDetails.ThreeDSecure createTxnDetailsThreeDSecure() {
        return new TxnDetails.ThreeDSecure();
    }

    /**
     * Create an instance of {@link TxnDetails.LineItemDetail }
     * 
     */
    public TxnDetails.LineItemDetail createTxnDetailsLineItemDetail() {
        return new TxnDetails.LineItemDetail();
    }

    /**
     * Create an instance of {@link TxnDetails.LineItemDetail.Items }
     * 
     */
    public TxnDetails.LineItemDetail.Items createTxnDetailsLineItemDetailItems() {
        return new TxnDetails.LineItemDetail.Items();
    }

    /**
     * Create an instance of {@link TxnDetails.LineItemDetail.Shipping }
     * 
     */
    public TxnDetails.LineItemDetail.Shipping createTxnDetailsLineItemDetailShipping() {
        return new TxnDetails.LineItemDetail.Shipping();
    }

    /**
     * Create an instance of {@link TxnDetails.Order }
     * 
     */
    public TxnDetails.Order createTxnDetailsOrder() {
        return new TxnDetails.Order();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.OrderDetails }
     * 
     */
    public TxnDetails.Order.OrderDetails createTxnDetailsOrderOrderDetails() {
        return new TxnDetails.Order.OrderDetails();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.Recipient }
     * 
     */
    public TxnDetails.Order.Recipient createTxnDetailsOrderRecipient() {
        return new TxnDetails.Order.Recipient();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.Customer }
     * 
     */
    public TxnDetails.Order.Customer createTxnDetailsOrderCustomer() {
        return new TxnDetails.Order.Customer();
    }

    /**
     * Create an instance of {@link TxnDetails.AdditionalData }
     * 
     */
    public TxnDetails.AdditionalData createTxnDetailsAdditionalData() {
        return new TxnDetails.AdditionalData();
    }

    /**
     * Create an instance of {@link Request.Transaction }
     * 
     */
    public Request.Transaction createRequestTransaction() {
        return new Request.Transaction();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn }
     * 
     */
    public Request.Transaction.URUTxn createRequestTransactionURUTxn() {
        return new Request.Transaction.URUTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn }
     * 
     */
    public Request.Transaction.SmartVoucherTxn createRequestTransactionSmartVoucherTxn() {
        return new Request.Transaction.SmartVoucherTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.PartSpend }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.PartSpend createRequestTransactionSmartVoucherTxnPartSpend() {
        return new Request.Transaction.SmartVoucherTxn.PartSpend();
    }

    /**
     * Create an instance of {@link Request.Transaction.BatchInputTxn }
     * 
     */
    public Request.Transaction.BatchInputTxn createRequestTransactionBatchInputTxn() {
        return new Request.Transaction.BatchInputTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn }
     * 
     */
    public Request.Transaction.ContAuthTxn createRequestTransactionContAuthTxn() {
        return new Request.Transaction.ContAuthTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn.LastPayment }
     * 
     */
    public Request.Transaction.ContAuthTxn.LastPayment createRequestTransactionContAuthTxnLastPayment() {
        return new Request.Transaction.ContAuthTxn.LastPayment();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn.FirstPayment }
     * 
     */
    public Request.Transaction.ContAuthTxn.FirstPayment createRequestTransactionContAuthTxnFirstPayment() {
        return new Request.Transaction.ContAuthTxn.FirstPayment();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn }
     * 
     */
    public Request.Transaction.HpsTxn createRequestTransactionHpsTxn() {
        return new Request.Transaction.HpsTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card }
     * 
     */
    public Request.Transaction.HpsTxn.Card createRequestTransactionHpsTxnCard() {
        return new Request.Transaction.HpsTxn.Card();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs createRequestTransactionHpsTxnCardCv2Avs() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.ChequeTxn }
     * 
     */
    public Request.Transaction.ChequeTxn createRequestTransactionChequeTxn() {
        return new Request.Transaction.ChequeTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn }
     * 
     */
    public Request.Transaction.CardTxn createRequestTransactionCardTxn() {
        return new Request.Transaction.CardTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card }
     * 
     */
    public Request.Transaction.CardTxn.Card createRequestTransactionCardTxnCard() {
        return new Request.Transaction.CardTxn.Card();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs createRequestTransactionCardTxnCardCv2Avs() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy createRequestTransactionCardTxnCardCv2AvsExtendedPolicy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy();
    }

    /**
     * Create an instance of {@link Request.UserAgent }
     * 
     */
    public Request.UserAgent createRequestUserAgent() {
        return new Request.UserAgent();
    }

    /**
     * Create an instance of {@link Request.UserAgent.Libraries }
     * 
     */
    public Request.UserAgent.Libraries createRequestUserAgentLibraries() {
        return new Request.UserAgent.Libraries();
    }

    /**
     * Create an instance of {@link Gift }
     * 
     */
    public Gift createGift() {
        return new Gift();
    }

    /**
     * Create an instance of {@link Request.Authentication }
     * 
     */
    public Request.Authentication createRequestAuthentication() {
        return new Request.Authentication();
    }

    /**
     * Create an instance of {@link TxnDetails.Amount }
     * 
     */
    public TxnDetails.Amount createTxnDetailsAmount() {
        return new TxnDetails.Amount();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link LineItemType }
     * 
     */
    public LineItemType createLineItemType() {
        return new LineItemType();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ShippingType }
     * 
     */
    public ShippingType createShippingType() {
        return new ShippingType();
    }

    /**
     * Create an instance of {@link TxnDetails.AirlinesDetails.Passenger }
     * 
     */
    public TxnDetails.AirlinesDetails.Passenger createTxnDetailsAirlinesDetailsPassenger() {
        return new TxnDetails.AirlinesDetails.Passenger();
    }

    /**
     * Create an instance of {@link TxnDetails.AirlinesDetails.FlightLeg }
     * 
     */
    public TxnDetails.AirlinesDetails.FlightLeg createTxnDetailsAirlinesDetailsFlightLeg() {
        return new TxnDetails.AirlinesDetails.FlightLeg();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan.CustomerInformation }
     * 
     */
    public TxnDetails.The3RdMan.CustomerInformation createTxnDetailsThe3RdManCustomerInformation() {
        return new TxnDetails.The3RdMan.CustomerInformation();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan.BillingAddress }
     * 
     */
    public TxnDetails.The3RdMan.BillingAddress createTxnDetailsThe3RdManBillingAddress() {
        return new TxnDetails.The3RdMan.BillingAddress();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan.DeliveryAddress }
     * 
     */
    public TxnDetails.The3RdMan.DeliveryAddress createTxnDetailsThe3RdManDeliveryAddress() {
        return new TxnDetails.The3RdMan.DeliveryAddress();
    }

    /**
     * Create an instance of {@link TxnDetails.The3RdMan.OrderInformation.Products.Product }
     * 
     */
    public TxnDetails.The3RdMan.OrderInformation.Products.Product createTxnDetailsThe3RdManOrderInformationProductsProduct() {
        return new TxnDetails.The3RdMan.OrderInformation.Products.Product();
    }

    /**
     * Create an instance of {@link TxnDetails.ThreeDSecure.Browser }
     * 
     */
    public TxnDetails.ThreeDSecure.Browser createTxnDetailsThreeDSecureBrowser() {
        return new TxnDetails.ThreeDSecure.Browser();
    }

    /**
     * Create an instance of {@link TxnDetails.LineItemDetail.Items.Item }
     * 
     */
    public TxnDetails.LineItemDetail.Items.Item createTxnDetailsLineItemDetailItemsItem() {
        return new TxnDetails.LineItemDetail.Items.Item();
    }

    /**
     * Create an instance of {@link TxnDetails.LineItemDetail.Shipping.AddressDetail }
     * 
     */
    public TxnDetails.LineItemDetail.Shipping.AddressDetail createTxnDetailsLineItemDetailShippingAddressDetail() {
        return new TxnDetails.LineItemDetail.Shipping.AddressDetail();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.OrderDetails.LineItem }
     * 
     */
    public TxnDetails.Order.OrderDetails.LineItem createTxnDetailsOrderOrderDetailsLineItem() {
        return new TxnDetails.Order.OrderDetails.LineItem();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.Recipient.LineItem }
     * 
     */
    public TxnDetails.Order.Recipient.LineItem createTxnDetailsOrderRecipientLineItem() {
        return new TxnDetails.Order.Recipient.LineItem();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.Customer.Company }
     * 
     */
    public TxnDetails.Order.Customer.Company createTxnDetailsOrderCustomerCompany() {
        return new TxnDetails.Order.Customer.Company();
    }

    /**
     * Create an instance of {@link TxnDetails.Order.Customer.CustomerHistory }
     * 
     */
    public TxnDetails.Order.Customer.CustomerHistory createTxnDetailsOrderCustomerCustomerHistory() {
        return new TxnDetails.Order.Customer.CustomerHistory();
    }

    /**
     * Create an instance of {@link TxnDetails.AdditionalData.CustomerInfo }
     * 
     */
    public TxnDetails.AdditionalData.CustomerInfo createTxnDetailsAdditionalDataCustomerInfo() {
        return new TxnDetails.AdditionalData.CustomerInfo();
    }

    /**
     * Create an instance of {@link Request.Transaction.DirectDebitTxn }
     * 
     */
    public Request.Transaction.DirectDebitTxn createRequestTransactionDirectDebitTxn() {
        return new Request.Transaction.DirectDebitTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.HistoricTxn }
     * 
     */
    public Request.Transaction.HistoricTxn createRequestTransactionHistoricTxn() {
        return new Request.Transaction.HistoricTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.DirectCreditTxn }
     * 
     */
    public Request.Transaction.DirectCreditTxn createRequestTransactionDirectCreditTxn() {
        return new Request.Transaction.DirectCreditTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.Basic }
     * 
     */
    public Request.Transaction.URUTxn.Basic createRequestTransactionURUTxnBasic() {
        return new Request.Transaction.URUTxn.Basic();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.Passport }
     * 
     */
    public Request.Transaction.URUTxn.Passport createRequestTransactionURUTxnPassport() {
        return new Request.Transaction.URUTxn.Passport();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.Electric }
     * 
     */
    public Request.Transaction.URUTxn.Electric createRequestTransactionURUTxnElectric() {
        return new Request.Transaction.URUTxn.Electric();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.Telephone }
     * 
     */
    public Request.Transaction.URUTxn.Telephone createRequestTransactionURUTxnTelephone() {
        return new Request.Transaction.URUTxn.Telephone();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.Driver }
     * 
     */
    public Request.Transaction.URUTxn.Driver createRequestTransactionURUTxnDriver() {
        return new Request.Transaction.URUTxn.Driver();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.Employment }
     * 
     */
    public Request.Transaction.URUTxn.Employment createRequestTransactionURUTxnEmployment() {
        return new Request.Transaction.URUTxn.Employment();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.CreditDebitCard }
     * 
     */
    public Request.Transaction.URUTxn.CreditDebitCard createRequestTransactionURUTxnCreditDebitCard() {
        return new Request.Transaction.URUTxn.CreditDebitCard();
    }

    /**
     * Create an instance of {@link Request.Transaction.URUTxn.InternationalPassport }
     * 
     */
    public Request.Transaction.URUTxn.InternationalPassport createRequestTransactionURUTxnInternationalPassport() {
        return new Request.Transaction.URUTxn.InternationalPassport();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.Purchase }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.Purchase createRequestTransactionSmartVoucherTxnPurchase() {
        return new Request.Transaction.SmartVoucherTxn.Purchase();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.Redeem }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.Redeem createRequestTransactionSmartVoucherTxnRedeem() {
        return new Request.Transaction.SmartVoucherTxn.Redeem();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.Enquiry }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.Enquiry createRequestTransactionSmartVoucherTxnEnquiry() {
        return new Request.Transaction.SmartVoucherTxn.Enquiry();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.Add }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.Add createRequestTransactionSmartVoucherTxnAdd() {
        return new Request.Transaction.SmartVoucherTxn.Add();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.Subtract }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.Subtract createRequestTransactionSmartVoucherTxnSubtract() {
        return new Request.Transaction.SmartVoucherTxn.Subtract();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.PartSpend.Purchase }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.PartSpend.Purchase createRequestTransactionSmartVoucherTxnPartSpendPurchase() {
        return new Request.Transaction.SmartVoucherTxn.PartSpend.Purchase();
    }

    /**
     * Create an instance of {@link Request.Transaction.SmartVoucherTxn.PartSpend.Redeem }
     * 
     */
    public Request.Transaction.SmartVoucherTxn.PartSpend.Redeem createRequestTransactionSmartVoucherTxnPartSpendRedeem() {
        return new Request.Transaction.SmartVoucherTxn.PartSpend.Redeem();
    }

    /**
     * Create an instance of {@link Request.Transaction.BatchInputTxn.Batchfile }
     * 
     */
    public Request.Transaction.BatchInputTxn.Batchfile createRequestTransactionBatchInputTxnBatchfile() {
        return new Request.Transaction.BatchInputTxn.Batchfile();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn.Amount }
     * 
     */
    public Request.Transaction.ContAuthTxn.Amount createRequestTransactionContAuthTxnAmount() {
        return new Request.Transaction.ContAuthTxn.Amount();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn.Flagging }
     * 
     */
    public Request.Transaction.ContAuthTxn.Flagging createRequestTransactionContAuthTxnFlagging() {
        return new Request.Transaction.ContAuthTxn.Flagging();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn.LastPayment.Amount }
     * 
     */
    public Request.Transaction.ContAuthTxn.LastPayment.Amount createRequestTransactionContAuthTxnLastPaymentAmount() {
        return new Request.Transaction.ContAuthTxn.LastPayment.Amount();
    }

    /**
     * Create an instance of {@link Request.Transaction.ContAuthTxn.FirstPayment.Amount }
     * 
     */
    public Request.Transaction.ContAuthTxn.FirstPayment.Amount createRequestTransactionContAuthTxnFirstPaymentAmount() {
        return new Request.Transaction.ContAuthTxn.FirstPayment.Amount();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.CardDetails }
     * 
     */
    public Request.Transaction.HpsTxn.CardDetails createRequestTransactionHpsTxnCardDetails() {
        return new Request.Transaction.HpsTxn.CardDetails();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicyCv2Policy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicyPostcodePolicy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicyAddressPolicy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.ChequeTxn.Cheque }
     * 
     */
    public Request.Transaction.ChequeTxn.Cheque createRequestTransactionChequeTxnCheque() {
        return new Request.Transaction.ChequeTxn.Cheque();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Authcode }
     * 
     */
    public Request.Transaction.CardTxn.Authcode createRequestTransactionCardTxnAuthcode() {
        return new Request.Transaction.CardTxn.Authcode();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.CardDetails }
     * 
     */
    public Request.Transaction.CardTxn.CardDetails createRequestTransactionCardTxnCardDetails() {
        return new Request.Transaction.CardTxn.CardDetails();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy createRequestTransactionCardTxnCardCv2AvsExtendedPolicyCv2Policy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy createRequestTransactionCardTxnCardCv2AvsExtendedPolicyPostcodePolicy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy createRequestTransactionCardTxnCardCv2AvsExtendedPolicyAddressPolicy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy();
    }

    /**
     * Create an instance of {@link Request.UserAgent.Environment }
     * 
     */
    public Request.UserAgent.Environment createRequestUserAgentEnvironment() {
        return new Request.UserAgent.Environment();
    }

    /**
     * Create an instance of {@link Request.UserAgent.Architecture }
     * 
     */
    public Request.UserAgent.Architecture createRequestUserAgentArchitecture() {
        return new Request.UserAgent.Architecture();
    }

    /**
     * Create an instance of {@link Request.UserAgent.Language }
     * 
     */
    public Request.UserAgent.Language createRequestUserAgentLanguage() {
        return new Request.UserAgent.Language();
    }

    /**
     * Create an instance of {@link Request.UserAgent.Libraries.Lib }
     * 
     */
    public Request.UserAgent.Libraries.Lib createRequestUserAgentLibrariesLib() {
        return new Request.UserAgent.Libraries.Lib();
    }

}
