//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 04:25:52 PM EDT 
//


package com.mhe.rest.datacash.request.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link TxnDetails }
     * 
     */
    public TxnDetails createTxnDetails() {
        return new TxnDetails();
    }

    /**
     * Create an instance of {@link TxnDetails.ThreeDSecure }
     * 
     */
    public TxnDetails.ThreeDSecure createTxnDetailsThreeDSecure() {
        return new TxnDetails.ThreeDSecure();
    }

    /**
     * Create an instance of {@link TxnDetails.AdditionalData }
     * 
     */
    public TxnDetails.AdditionalData createTxnDetailsAdditionalData() {
        return new TxnDetails.AdditionalData();
    }

    /**
     * Create an instance of {@link Request.Transaction }
     * 
     */
    public Request.Transaction createRequestTransaction() {
        return new Request.Transaction();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn }
     * 
     */
    public Request.Transaction.HpsTxn createRequestTransactionHpsTxn() {
        return new Request.Transaction.HpsTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card }
     * 
     */
    public Request.Transaction.HpsTxn.Card createRequestTransactionHpsTxnCard() {
        return new Request.Transaction.HpsTxn.Card();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs createRequestTransactionHpsTxnCardCv2Avs() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn }
     * 
     */
    public Request.Transaction.CardTxn createRequestTransactionCardTxn() {
        return new Request.Transaction.CardTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card }
     * 
     */
    public Request.Transaction.CardTxn.Card createRequestTransactionCardTxnCard() {
        return new Request.Transaction.CardTxn.Card();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs createRequestTransactionCardTxnCardCv2Avs() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy createRequestTransactionCardTxnCardCv2AvsExtendedPolicy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy();
    }

    /**
     * Create an instance of {@link Request.Authentication }
     * 
     */
    public Request.Authentication createRequestAuthentication() {
        return new Request.Authentication();
    }

    /**
     * Create an instance of {@link TxnDetails.Amount }
     * 
     */
    public TxnDetails.Amount createTxnDetailsAmount() {
        return new TxnDetails.Amount();
    }

    /**
     * Create an instance of {@link TxnDetails.ThreeDSecure.Browser }
     * 
     */
    public TxnDetails.ThreeDSecure.Browser createTxnDetailsThreeDSecureBrowser() {
        return new TxnDetails.ThreeDSecure.Browser();
    }

    /**
     * Create an instance of {@link TxnDetails.AdditionalData.CustomerInfo }
     * 
     */
    public TxnDetails.AdditionalData.CustomerInfo createTxnDetailsAdditionalDataCustomerInfo() {
        return new TxnDetails.AdditionalData.CustomerInfo();
    }

    /**
     * Create an instance of {@link Request.Transaction.HistoricTxn }
     * 
     */
    public Request.Transaction.HistoricTxn createRequestTransactionHistoricTxn() {
        return new Request.Transaction.HistoricTxn();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.CardDetails }
     * 
     */
    public Request.Transaction.HpsTxn.CardDetails createRequestTransactionHpsTxnCardDetails() {
        return new Request.Transaction.HpsTxn.CardDetails();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.DynamicData }
     * 
     */
    public Request.Transaction.HpsTxn.DynamicData createRequestTransactionHpsTxnDynamicData() {
        return new Request.Transaction.HpsTxn.DynamicData();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicyCv2Policy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicyPostcodePolicy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy }
     * 
     */
    public Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy createRequestTransactionHpsTxnCardCv2AvsExtendedPolicyAddressPolicy() {
        return new Request.Transaction.HpsTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.CardDetails }
     * 
     */
    public Request.Transaction.CardTxn.CardDetails createRequestTransactionCardTxnCardDetails() {
        return new Request.Transaction.CardTxn.CardDetails();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy createRequestTransactionCardTxnCardCv2AvsExtendedPolicyCv2Policy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.Cv2Policy();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy createRequestTransactionCardTxnCardCv2AvsExtendedPolicyPostcodePolicy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.PostcodePolicy();
    }

    /**
     * Create an instance of {@link Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy }
     * 
     */
    public Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy createRequestTransactionCardTxnCardCv2AvsExtendedPolicyAddressPolicy() {
        return new Request.Transaction.CardTxn.Card.Cv2Avs.ExtendedPolicy.AddressPolicy();
    }

}
