//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 04:25:52 PM EDT 
//


package com.mhe.rest.datacash.request.entity;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchantreference" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="6"/>
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="amount" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
 *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="custom_data" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="capturemethod" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ecomm"/>
 *               &lt;enumeration value="cnp"/>
 *               &lt;enumeration value="cont_auth"/>
 *               &lt;enumeration value="ivr"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AdditionalData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="addendumdata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="risk_bypass" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Y"/>
 *                         &lt;enumeration value="N"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CustomerInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="customer_ip_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ThreeDSecure" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="verify">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="yes"/>
 *                         &lt;enumeration value="no"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="merchant_url" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="purchase_desc" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="purchase_datetime" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="Browser" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="device_category">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="0"/>
 *                                   &lt;enumeration value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="accept_headers" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="user_agent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="num_installments" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="recur_expiry" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="recur_frequency" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allocated_reference" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="txndate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="txntime" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="vgismessage" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "merchantreference",
    "amount",
    "customData",
    "capturemethod",
    "additionalData",
    "threeDSecure",
    "allocatedReference",
    "mode",
    "txndate",
    "txntime",
    "vgismessage"
})
@XmlRootElement(name = "TxnDetails")
public class TxnDetails {

    protected String merchantreference;
    protected TxnDetails.Amount amount;
    @XmlElement(name = "custom_data")
    protected String customData;
    protected String capturemethod;
    @XmlElement(name = "AdditionalData")
    protected TxnDetails.AdditionalData additionalData;
    @XmlElement(name = "ThreeDSecure")
    protected TxnDetails.ThreeDSecure threeDSecure;
    @XmlElement(name = "allocated_reference", required = true)
    protected Object allocatedReference;
    @XmlElement(required = true)
    protected Object mode;
    @XmlElement(required = true)
    protected Object txndate;
    @XmlElement(required = true)
    protected Object txntime;
    @XmlElement(required = true)
    protected Object vgismessage;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the merchantreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantreference() {
        return merchantreference;
    }

    /**
     * Sets the value of the merchantreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantreference(String value) {
        this.merchantreference = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link TxnDetails.Amount }
     *     
     */
    public TxnDetails.Amount getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnDetails.Amount }
     *     
     */
    public void setAmount(TxnDetails.Amount value) {
        this.amount = value;
    }

    /**
     * Gets the value of the customData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomData() {
        return customData;
    }

    /**
     * Sets the value of the customData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomData(String value) {
        this.customData = value;
    }

    /**
     * Gets the value of the capturemethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapturemethod() {
        return capturemethod;
    }

    /**
     * Sets the value of the capturemethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapturemethod(String value) {
        this.capturemethod = value;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * @return
     *     possible object is
     *     {@link TxnDetails.AdditionalData }
     *     
     */
    public TxnDetails.AdditionalData getAdditionalData() {
        return additionalData;
    }

    /**
     * Sets the value of the additionalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnDetails.AdditionalData }
     *     
     */
    public void setAdditionalData(TxnDetails.AdditionalData value) {
        this.additionalData = value;
    }

    /**
     * Gets the value of the threeDSecure property.
     * 
     * @return
     *     possible object is
     *     {@link TxnDetails.ThreeDSecure }
     *     
     */
    public TxnDetails.ThreeDSecure getThreeDSecure() {
        return threeDSecure;
    }

    /**
     * Sets the value of the threeDSecure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnDetails.ThreeDSecure }
     *     
     */
    public void setThreeDSecure(TxnDetails.ThreeDSecure value) {
        this.threeDSecure = value;
    }

    /**
     * Gets the value of the allocatedReference property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAllocatedReference() {
        return allocatedReference;
    }

    /**
     * Sets the value of the allocatedReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAllocatedReference(Object value) {
        this.allocatedReference = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMode(Object value) {
        this.mode = value;
    }

    /**
     * Gets the value of the txndate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTxndate() {
        return txndate;
    }

    /**
     * Sets the value of the txndate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTxndate(Object value) {
        this.txndate = value;
    }

    /**
     * Gets the value of the txntime property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTxntime() {
        return txntime;
    }

    /**
     * Sets the value of the txntime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTxntime(Object value) {
        this.txntime = value;
    }

    /**
     * Gets the value of the vgismessage property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVgismessage() {
        return vgismessage;
    }

    /**
     * Sets the value of the vgismessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVgismessage(Object value) {
        this.vgismessage = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="addendumdata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="risk_bypass" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Y"/>
     *               &lt;enumeration value="N"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CustomerInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="customer_ip_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addendumdata",
        "riskBypass",
        "customerInfo"
    })
    public static class AdditionalData {

        protected String addendumdata;
        @XmlElement(name = "risk_bypass")
        protected String riskBypass;
        @XmlElement(name = "CustomerInfo")
        protected TxnDetails.AdditionalData.CustomerInfo customerInfo;

        /**
         * Gets the value of the addendumdata property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddendumdata() {
            return addendumdata;
        }

        /**
         * Sets the value of the addendumdata property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddendumdata(String value) {
            this.addendumdata = value;
        }

        /**
         * Gets the value of the riskBypass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRiskBypass() {
            return riskBypass;
        }

        /**
         * Sets the value of the riskBypass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRiskBypass(String value) {
            this.riskBypass = value;
        }

        /**
         * Gets the value of the customerInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TxnDetails.AdditionalData.CustomerInfo }
         *     
         */
        public TxnDetails.AdditionalData.CustomerInfo getCustomerInfo() {
            return customerInfo;
        }

        /**
         * Sets the value of the customerInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TxnDetails.AdditionalData.CustomerInfo }
         *     
         */
        public void setCustomerInfo(TxnDetails.AdditionalData.CustomerInfo value) {
            this.customerInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="customer_ip_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customerIpAddress"
        })
        public static class CustomerInfo {

            @XmlElement(name = "customer_ip_address", required = true)
            protected String customerIpAddress;

            /**
             * Gets the value of the customerIpAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerIpAddress() {
                return customerIpAddress;
            }

            /**
             * Sets the value of the customerIpAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerIpAddress(String value) {
                this.customerIpAddress = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
     *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Amount {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "currency")
        protected String currency;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="verify">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="yes"/>
     *               &lt;enumeration value="no"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="merchant_url" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="purchase_desc" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="purchase_datetime" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="Browser" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="device_category">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="0"/>
     *                         &lt;enumeration value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="accept_headers" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="user_agent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="num_installments" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="recur_expiry" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="recur_frequency" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "verify",
        "merchantUrl",
        "purchaseDesc",
        "purchaseDatetime",
        "browser",
        "numInstallments",
        "recurExpiry",
        "recurFrequency"
    })
    public static class ThreeDSecure {

        @XmlElement(required = true)
        protected String verify;
        @XmlElement(name = "merchant_url", required = true)
        protected Object merchantUrl;
        @XmlElement(name = "purchase_desc", required = true)
        protected Object purchaseDesc;
        @XmlElement(name = "purchase_datetime")
        protected Object purchaseDatetime;
        @XmlElement(name = "Browser")
        protected TxnDetails.ThreeDSecure.Browser browser;
        @XmlElement(name = "num_installments")
        protected Object numInstallments;
        @XmlElement(name = "recur_expiry")
        protected Object recurExpiry;
        @XmlElement(name = "recur_frequency")
        protected Object recurFrequency;

        /**
         * Gets the value of the verify property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerify() {
            return verify;
        }

        /**
         * Sets the value of the verify property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerify(String value) {
            this.verify = value;
        }

        /**
         * Gets the value of the merchantUrl property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getMerchantUrl() {
            return merchantUrl;
        }

        /**
         * Sets the value of the merchantUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setMerchantUrl(Object value) {
            this.merchantUrl = value;
        }

        /**
         * Gets the value of the purchaseDesc property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPurchaseDesc() {
            return purchaseDesc;
        }

        /**
         * Sets the value of the purchaseDesc property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPurchaseDesc(Object value) {
            this.purchaseDesc = value;
        }

        /**
         * Gets the value of the purchaseDatetime property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPurchaseDatetime() {
            return purchaseDatetime;
        }

        /**
         * Sets the value of the purchaseDatetime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPurchaseDatetime(Object value) {
            this.purchaseDatetime = value;
        }

        /**
         * Gets the value of the browser property.
         * 
         * @return
         *     possible object is
         *     {@link TxnDetails.ThreeDSecure.Browser }
         *     
         */
        public TxnDetails.ThreeDSecure.Browser getBrowser() {
            return browser;
        }

        /**
         * Sets the value of the browser property.
         * 
         * @param value
         *     allowed object is
         *     {@link TxnDetails.ThreeDSecure.Browser }
         *     
         */
        public void setBrowser(TxnDetails.ThreeDSecure.Browser value) {
            this.browser = value;
        }

        /**
         * Gets the value of the numInstallments property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNumInstallments() {
            return numInstallments;
        }

        /**
         * Sets the value of the numInstallments property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNumInstallments(Object value) {
            this.numInstallments = value;
        }

        /**
         * Gets the value of the recurExpiry property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getRecurExpiry() {
            return recurExpiry;
        }

        /**
         * Sets the value of the recurExpiry property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setRecurExpiry(Object value) {
            this.recurExpiry = value;
        }

        /**
         * Gets the value of the recurFrequency property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getRecurFrequency() {
            return recurFrequency;
        }

        /**
         * Sets the value of the recurFrequency property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setRecurFrequency(Object value) {
            this.recurFrequency = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="device_category">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="0"/>
         *               &lt;enumeration value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="accept_headers" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="user_agent" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "deviceCategory",
            "acceptHeaders",
            "userAgent"
        })
        public static class Browser {

            @XmlElement(name = "device_category", required = true)
            protected String deviceCategory;
            @XmlElement(name = "accept_headers", required = true)
            protected Object acceptHeaders;
            @XmlElement(name = "user_agent", required = true)
            protected Object userAgent;

            /**
             * Gets the value of the deviceCategory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDeviceCategory() {
                return deviceCategory;
            }

            /**
             * Sets the value of the deviceCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDeviceCategory(String value) {
                this.deviceCategory = value;
            }

            /**
             * Gets the value of the acceptHeaders property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getAcceptHeaders() {
                return acceptHeaders;
            }

            /**
             * Sets the value of the acceptHeaders property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setAcceptHeaders(Object value) {
                this.acceptHeaders = value;
            }

            /**
             * Gets the value of the userAgent property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getUserAgent() {
                return userAgent;
            }

            /**
             * Sets the value of the userAgent property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setUserAgent(Object value) {
                this.userAgent = value;
            }

        }

    }

}
