//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 02:51:53 PM EDT 
//


package com.mhe.rest.datacash.response.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult }
     * 
     */
    public Response.QueryTxnResult createResponseQueryTxnResult() {
        return new Response.QueryTxnResult();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult.Card }
     * 
     */
    public Response.QueryTxnResult.Card createResponseQueryTxnResultCard() {
        return new Response.QueryTxnResult.Card();
    }

    /**
     * Create an instance of {@link Response.HpsTxn }
     * 
     */
    public Response.HpsTxn createResponseHpsTxn() {
        return new Response.HpsTxn();
    }

    /**
     * Create an instance of {@link Response.HpsTxn.CaptureAttempts }
     * 
     */
    public Response.HpsTxn.CaptureAttempts createResponseHpsTxnCaptureAttempts() {
        return new Response.HpsTxn.CaptureAttempts();
    }

    /**
     * Create an instance of {@link Response.HpsTxn.AuthAttempts }
     * 
     */
    public Response.HpsTxn.AuthAttempts createResponseHpsTxnAuthAttempts() {
        return new Response.HpsTxn.AuthAttempts();
    }

    /**
     * Create an instance of {@link Response.CardTxn }
     * 
     */
    public Response.CardTxn createResponseCardTxn() {
        return new Response.CardTxn();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs }
     * 
     */
    public Response.CardTxn.Cv2Avs createResponseCardTxnCv2Avs() {
        return new Response.CardTxn.Cv2Avs();
    }

    /**
     * Create an instance of {@link Response.CardTxn.EbitGuard }
     * 
     */
    public Response.CardTxn.EbitGuard createResponseCardTxnEbitGuard() {
        return new Response.CardTxn.EbitGuard();
    }

    /**
     * Create an instance of {@link Response.HistoricTxn }
     * 
     */
    public Response.HistoricTxn createResponseHistoricTxn() {
        return new Response.HistoricTxn();
    }

    /**
     * Create an instance of {@link Response.Reason }
     * 
     */
    public Response.Reason createResponseReason() {
        return new Response.Reason();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult.MassPayTxn }
     * 
     */
    public Response.QueryTxnResult.MassPayTxn createResponseQueryTxnResultMassPayTxn() {
        return new Response.QueryTxnResult.MassPayTxn();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult.ContAuthTxn }
     * 
     */
    public Response.QueryTxnResult.ContAuthTxn createResponseQueryTxnResultContAuthTxn() {
        return new Response.QueryTxnResult.ContAuthTxn();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult.ThreeDSecure }
     * 
     */
    public Response.QueryTxnResult.ThreeDSecure createResponseQueryTxnResultThreeDSecure() {
        return new Response.QueryTxnResult.ThreeDSecure();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult.Amount }
     * 
     */
    public Response.QueryTxnResult.Amount createResponseQueryTxnResultAmount() {
        return new Response.QueryTxnResult.Amount();
    }

    /**
     * Create an instance of {@link Response.QueryTxnResult.Card.Cv2Avs }
     * 
     */
    public Response.QueryTxnResult.Card.Cv2Avs createResponseQueryTxnResultCardCv2Avs() {
        return new Response.QueryTxnResult.Card.Cv2Avs();
    }

    /**
     * Create an instance of {@link Response.HpsTxn.DynamicCapture }
     * 
     */
    public Response.HpsTxn.DynamicCapture createResponseHpsTxnDynamicCapture() {
        return new Response.HpsTxn.DynamicCapture();
    }

    /**
     * Create an instance of {@link Response.HpsTxn.CaptureAttempts.Attempt }
     * 
     */
    public Response.HpsTxn.CaptureAttempts.Attempt createResponseHpsTxnCaptureAttemptsAttempt() {
        return new Response.HpsTxn.CaptureAttempts.Attempt();
    }

    /**
     * Create an instance of {@link Response.HpsTxn.AuthAttempts.Attempt }
     * 
     */
    public Response.HpsTxn.AuthAttempts.Attempt createResponseHpsTxnAuthAttemptsAttempt() {
        return new Response.HpsTxn.AuthAttempts.Attempt();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Authcode }
     * 
     */
    public Response.CardTxn.Authcode createResponseCardTxnAuthcode() {
        return new Response.CardTxn.Authcode();
    }

    /**
     * Create an instance of {@link Response.CardTxn.ThreeDSecure }
     * 
     */
    public Response.CardTxn.ThreeDSecure createResponseCardTxnThreeDSecure() {
        return new Response.CardTxn.ThreeDSecure();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.Cv2AvsStatus }
     * 
     */
    public Response.CardTxn.Cv2Avs.Cv2AvsStatus createResponseCardTxnCv2AvsCv2AvsStatus() {
        return new Response.CardTxn.Cv2Avs.Cv2AvsStatus();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.Cv2Policy }
     * 
     */
    public Response.CardTxn.Cv2Avs.Cv2Policy createResponseCardTxnCv2AvsCv2Policy() {
        return new Response.CardTxn.Cv2Avs.Cv2Policy();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.PostcodePolicy }
     * 
     */
    public Response.CardTxn.Cv2Avs.PostcodePolicy createResponseCardTxnCv2AvsPostcodePolicy() {
        return new Response.CardTxn.Cv2Avs.PostcodePolicy();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.AddressPolicy }
     * 
     */
    public Response.CardTxn.Cv2Avs.AddressPolicy createResponseCardTxnCv2AvsAddressPolicy() {
        return new Response.CardTxn.Cv2Avs.AddressPolicy();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.Cv2Result }
     * 
     */
    public Response.CardTxn.Cv2Avs.Cv2Result createResponseCardTxnCv2AvsCv2Result() {
        return new Response.CardTxn.Cv2Avs.Cv2Result();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.PostcodeResult }
     * 
     */
    public Response.CardTxn.Cv2Avs.PostcodeResult createResponseCardTxnCv2AvsPostcodeResult() {
        return new Response.CardTxn.Cv2Avs.PostcodeResult();
    }

    /**
     * Create an instance of {@link Response.CardTxn.Cv2Avs.AddressResult }
     * 
     */
    public Response.CardTxn.Cv2Avs.AddressResult createResponseCardTxnCv2AvsAddressResult() {
        return new Response.CardTxn.Cv2Avs.AddressResult();
    }

    /**
     * Create an instance of {@link Response.CardTxn.EbitGuard.FraudStatus }
     * 
     */
    public Response.CardTxn.EbitGuard.FraudStatus createResponseCardTxnEbitGuardFraudStatus() {
        return new Response.CardTxn.EbitGuard.FraudStatus();
    }

}
